CREATE TABLE [BOOKS](
[ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
[BOOKNAME] VARCHAR(250) NOT NULL,
[BOOKLINK] VARCHAR(250),
[CATEGORY_ID] INTEGER CONSTRAINT [FK_BOOKS_CATEGORY_ID] REFERENCES CATEGORIES([ID]));

CREATE TABLE [CATEGORIES](
[ID] INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
[CATEGORYNAME] VARCHAR(250) NOT NULL,
[PARENT_ID] INTEGER CONSTRAINT [FK_CATEGORIES_PARENTID] REFERENCES CATEGORIES([ID]));